title: Pere Martra
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  AI Engineer & Researcher. Author of "Large Language Models Projects" (Apress) & "Rearchitecting LLMs" (Manning). Expert in Pruning, Efficiency & Fairness.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://peremartra.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: peremartra
github_username: peremartra

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
